version: '3.4'

services:
  milvusservice:
    container_name: milvus-service
    image: amfontys/milvusservice:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    