name: "Deploy Milvus Service to Google Cloud"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
          docker build -t europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/milvus-service/python:latest .
          docker push europe-west4-docker.pkg.dev/$GOOGLE_PROJECT/milvus-service/python:latest

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials autopilot-milvus-service --region europe-west4
          kubectl apply -f resources.yml

  load-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install K6
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install k6

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Connect to GKE Cluster
        run: |
          gcloud container clusters get-credentials autopilot-hotel-information-agent --region europe-west4 --project ${{ secrets.GOOGLE_PROJECT }}

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/hotel-information-agent

      - name: Get External IP
        run: |
          run: echo "EXTERNAL_IP=kubectl get svc python -o json | jq .status.loadBalancer.ingress[0].ip" >> $GITHUB_ENV

      - name: Login to Grafana
        run: |
          k6 login cloud --token ${{ secrets.K6_CLOUD_TOKEN }}

      - name: Run Load Tests
        run: |
          k6 cloud -u 10 -d 30s ${{ env.EXTERNAL_IP }}