name: Build, Push and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: milvus.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t milvus.azurecr.io/myapp:${{ github.sha }} .
          docker push milvus.azurecr.io/myapp:${{ github.sha }}
  deploy:  
    permissions:  
      contents: none  
    runs-on: ubuntu-latest  
    needs: build_and_push  

    steps:  

      # - name: Deploy to Azure Web App  
      #   id: deploy-to-webapp  
      #   uses: azure/webapps-deploy@v2  
      #   with:  
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}  
      #     publish-profile: ${{ secrets.MILVUS_AZURE_PUBLISH_PROFILE }}  
      #     images: 'milvus.azurecr.io/myapp:${{ github.sha }}'

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: 'milvus.azurecr.io/myapp:${{ github.sha }}'
          registry-login-server: milvus.azurecr.io
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: milvus-dverse-instance
          location: 'west us'